#! /bin/bash


if [[ $1 == 'qemu' ]]; then
  qemu-system-arm -M versatilepb -m 128M -nographic -s -S -kernel irq.elf &
elif [[ $1 == 'run' ]]; then
  arm-none-eabi-gdb -tui irq.elf
elif [[ $1 == "kill" ]]; then
  ps axf | grep qemu | grep -v grep | awk '{print "kill -9 " $1}' | sh
else
  echo "No command $1"
fi
